# Generated by Django 4.2.7 on 2026-01-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_signin_audit_logs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_timesta_40aa9a_idx',
            old_name='accounts_au_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_perform_8864c0_idx',
            old_name='accounts_au_perform_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_918219_idx',
            old_name='accounts_au_action_idx',
        ),
        migrations.RenameIndex(
            model_name='signinlog',
            new_name='accounts_si_timesta_7c572b_idx',
            old_name='accounts_si_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='signinlog',
            new_name='accounts_si_user_id_3763b5_idx',
            old_name='accounts_si_user_id_idx',
        ),
    ]
