# Generated by Django 4.2.17 on 2026-02-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_accounts_au_timesta_idx_accounts_au_timesta_40aa9a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cost_quota_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cost quota (USD)'),
        ),
        migrations.AddField(
            model_name='user',
            name='cost_used_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Cost used (USD)'),
        ),
        migrations.AlterField(
            model_name='signinlog',
            name='authentication_method',
            field=models.CharField(choices=[('local', 'Local'), ('azure_ad', 'Azure AD')], default='local', max_length=50),
        ),
    ]
