# Generated by Django 4.2.17 on 2026-02-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_cost_quota_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_document_converter',
            field=models.BooleanField(default=False, help_text='Grant access to the document conversion feature', verbose_name='Document Converter Access'),
        ),
    ]
