# Generated by Django 4.2.17 on 2026-02-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_has_document_converter'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinlog',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
