# Generated by Django 4.2.17 on 2026-03-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_has_presentation_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presentation_quality_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('pro', 'Pro'), ('gamma', 'Gamma')], default='standard', help_text='Quality tier assigned to this user for presentations', max_length=20, verbose_name='Presentation Quality Tier'),
        ),
    ]
