# Generated by Django 4.2.17 on 2026-03-24 17:58

from django.db import migrations, models


def migrate_single_tier_to_multi(apps, schema_editor):
    """Convert old single presentation_quality_tier to new multi-tier JSONField."""
    User = apps.get_model('accounts', 'User')
    TIER_MAP = {
        'standard': ['pro'],       # standard → pro
        'pro': ['pro'],            # pro stays pro
        'gamma': ['gini_pro'],     # gamma → gini_pro
    }
    for user in User.objects.all():
        old_tier = getattr(user, 'presentation_quality_tier', 'standard') or 'standard'
        user.presentation_quality_tiers = TIER_MAP.get(old_tier, ['pro'])
        user.save(update_fields=['presentation_quality_tiers'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_presentation_quality_tier'),
    ]

    operations = [
        # Step 1: Add the new JSONField (with default=list so existing rows get [])
        migrations.AddField(
            model_name='user',
            name='presentation_quality_tiers',
            field=models.JSONField(blank=True, default=list, help_text='List of quality tiers assigned to this user, e.g. ["pro", "gini_pro"]', verbose_name='Presentation Quality Tiers'),
        ),
        # Step 2: Migrate data from old field to new field
        migrations.RunPython(migrate_single_tier_to_multi, migrations.RunPython.noop),
        # Step 3: Remove old field
        migrations.RemoveField(
            model_name='user',
            name='presentation_quality_tier',
        ),
    ]
