# Generated by Django 4.2.17 on 2026-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_cloud_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cloud_role',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('user_quota_changed', 'User Quota Changed'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('user_login', 'User Login'), ('admin_login', 'Admin Login'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('other', 'Other')], max_length=50),
        ),
    ]
