# Generated by Django 4.2.17 on 2026-07-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_cloud_role_alter_auditlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_presentation_creator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='presentation_quality_tiers',
        ),
    ]
