# Generated by Django 4.2.17 on 2026-07-20 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_user_has_presentation_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signinlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_in_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
