# Generated by Django 4.2.17 on 2026-07-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_fix_log_on_delete_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cost_quota_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Cost quota (USD)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cost_used_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Cost used (USD)'),
        ),
    ]
