# Generated by Django 4.2.17 on 2026-07-23 19:35

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_cost_quota_usd_alter_user_cost_used_usd'),
    ]

    operations = [
        # Required by the gin_trgm_ops opclass used below.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['action'], name='auditlog_action_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='signinlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='signinlog_username_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='user_username_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
