# Generated by Django 4.2.17 on 2026-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auditlog_auditlog_action_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='long_term_memory',
            field=models.TextField(blank=True, default=''),
        ),
    ]
