# Generated by Django 4.2.7 on 2026-01-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_userllmpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='llm_provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude'), ('llama', 'Meta Llama')], max_length=50),
        ),
    ]
