# Generated by Django 4.2.7 on 2026-01-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_llmusagelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmusagelog',
            options={},
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['user', 'created_at'], name='admin_porta_user_id_2df7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['provider'], name='admin_porta_provide_514f50_idx'),
        ),
    ]
