# Generated by Django 4.2.17 on 2026-02-08 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0009_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfig',
            options={'ordering': ['category', 'key'], 'verbose_name': 'App configuration', 'verbose_name_plural': 'App configurations'},
        ),
        migrations.AlterModelOptions(
            name='llmprovider',
            options={'ordering': ['sort_order', 'display_name']},
        ),
        migrations.AlterModelOptions(
            name='llmusagelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'LLM usage log', 'verbose_name_plural': 'LLM usage logs'},
        ),
        migrations.AlterModelOptions(
            name='userllmpermission',
            options={'ordering': ['llm_provider__sort_order']},
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('chat', 'Chat'), ('upload', 'Upload'), ('security', 'Security')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='If True, value is masked in admin UI'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='value_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='chat_mode',
            field=models.CharField(choices=[('general', 'General Chat'), ('code', 'Code Assistant'), ('summarize', 'Summarizer'), ('document', 'Document Q&A')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='original_token_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='summarized_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='extraction_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Size in bytes'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='api_endpoint',
            field=models.URLField(blank=True, default='', help_text='API endpoint URL. Leave blank for default.', max_length=500),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='api_key_env_var',
            field=models.CharField(blank=True, default='', help_text='Name of the .env variable holding the API key', max_length=100),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='api_version',
            field=models.CharField(blank=True, default='', help_text='API version string, e.g. "2024-12-01-preview"', max_length=30),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='display_name',
            field=models.CharField(help_text='Friendly label, e.g. "GPT-4.1 Mini"', max_length=200),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional provider-specific config as JSON'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='icon_name',
            field=models.CharField(blank=True, default='sparkles', help_text='Lucide icon name for the frontend', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Show as pre-selected for new users'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='model_name',
            field=models.CharField(help_text='Model identifier, e.g. "gpt-4.1-mini", "gemini-2.5-flash"', max_length=200),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='name',
            field=models.CharField(db_index=True, help_text='Slug used in URLs and permissions, e.g. "gpt4-mini"', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('azure_openai', 'Azure OpenAI'), ('openai', 'OpenAI'), ('google', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('ollama', 'Ollama (Local)'), ('huggingface', 'HuggingFace'), ('custom', 'Custom / OpenAI-compatible')], db_index=True, default='ollama', max_length=30),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower = shown first'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='Default system prompt for this model'),
        ),
        migrations.AlterField(
            model_name='llmusagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='llmusagelog',
            name='model',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llmusagelog',
            name='provider',
            field=models.CharField(db_index=True, help_text='Provider type string for quick filtering', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userllmpermission',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Permission expires at this time. NULL = never.', null=True),
        ),
        migrations.AlterField(
            model_name='userllmpermission',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userllmpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userllmpermission',
            name='llm_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='admin_portal.llmprovider'),
        ),
        migrations.AlterField(
            model_name='userllmpermission',
            name='quota_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Allowed usage in minutes. NULL = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='userllmpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
