# Generated by Django 4.2.17 on 2026-02-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0010_alter_appconfig_options_alter_llmprovider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='llm_provider',
            field=models.ForeignKey(blank=True, help_text='The model that generated this message (assistant) or that was selected when the user sent it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='admin_portal.llmprovider'),
        ),
    ]
