# Generated by Django 4.2.17 on 2026-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0011_add_llm_provider_to_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_mode',
            field=models.CharField(choices=[('general', 'General Chat'), ('code', 'Code Assistant'), ('summarize', 'Summarizer'), ('document', 'Document Q&A'), ('presentation', 'Presentation Creator')], db_index=True, default='general', max_length=20),
        ),
    ]
