# Generated by Django 4.2.17 on 2026-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0012_add_presentation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('azure_openai', 'Azure OpenAI'), ('azure_ai_foundry', 'Azure AI Foundry'), ('openai', 'OpenAI'), ('google', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('ollama', 'Ollama (Local)'), ('huggingface', 'HuggingFace'), ('custom', 'Custom / OpenAI-compatible')], db_index=True, default='ollama', max_length=30),
        ),
    ]
