# Generated by Django 4.2.17 on 2026-02-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0013_add_azure_ai_foundry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pptx_theme',
            field=models.CharField(blank=True, default='', help_text='Theme used for PPTX generation', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='pptx_url',
            field=models.CharField(blank=True, default='', help_text='URL to generated PPTX file', max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='style_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='Style suggestions from LLM'),
        ),
    ]
