# Generated by Django 4.2.17 on 2026-02-09 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0014_add_pptx_fields_to_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_format', models.CharField(max_length=20)),
                ('target_format', models.CharField(max_length=20)),
                ('quality', models.CharField(default='high', max_length=20)),
                ('input_file', models.FileField(upload_to='conversions/input/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='conversions/output/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('output_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='admin_porta_user_id_7159fc_idx'), models.Index(fields=['status', '-created_at'], name='admin_porta_status_d14d40_idx')],
            },
        ),
    ]
