# Generated by Django 4.2.17 on 2026-02-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0015_conversionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='encrypted_api_key',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted API key stored in DB (preferred)'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='api_key_env_var',
            field=models.CharField(blank=True, default='', help_text='Name of the .env variable holding the API key (fallback)', max_length=100),
        ),
    ]
