# Generated by Django 4.2.17 on 2026-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0016_add_encrypted_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('azure_openai', 'Azure OpenAI'), ('azure_ai_foundry', 'Azure AI Foundry'), ('openai', 'OpenAI'), ('google', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('ollama', 'Ollama (Local)'), ('huggingface', 'HuggingFace'), ('custom', 'Custom / OpenAI-compatible')], db_index=True, default='ollama', max_length=30),
        ),
    ]
