# Generated by Django 4.2.17 on 2026-03-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0017_expand_provider_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='input_cost_per_1m',
            field=models.FloatField(default=0.0, help_text='Cost per 1 million input (prompt) tokens in USD. e.g. 0.15 for GPT-4o-mini'),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='output_cost_per_1m',
            field=models.FloatField(default=0.0, help_text='Cost per 1 million output (completion) tokens in USD. e.g. 0.60 for GPT-4o-mini'),
        ),
    ]
