# Generated by Django 4.2.17 on 2026-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0019_presentationjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='presentationjob',
            new_name='admin_porta_user_id_73e21a_idx',
            old_name='admin_porta_user_id_pres_idx',
        ),
        migrations.RenameIndex(
            model_name='presentationjob',
            new_name='admin_porta_status_9fcf8b_idx',
            old_name='admin_porta_status_pres_idx',
        ),
        migrations.AddField(
            model_name='presentationjob',
            name='export_url',
            field=models.URLField(blank=True, default='', help_text='Gamma export download URL (PPTX/PDF/PNG)', max_length=500),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
