# Generated by Django 4.2.17 on 2026-03-24 17:59

from django.db import migrations, models


def rename_existing_tiers(apps, schema_editor):
    """Rename existing presentation job tiers: standard→pro, gamma→gini_pro."""
    PresentationJob = apps.get_model('admin_portal', 'PresentationJob')
    PresentationJob.objects.filter(quality_tier='standard').update(quality_tier='pro')
    PresentationJob.objects.filter(quality_tier='gamma').update(quality_tier='gini_pro')


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0020_add_export_url_to_presentationjob'),
    ]

    operations = [
        # First rename existing data
        migrations.RunPython(rename_existing_tiers, migrations.RunPython.noop),
        # Then update choices and default
        migrations.AlterField(
            model_name='presentationjob',
            name='quality_tier',
            field=models.CharField(choices=[('pro', 'Pro'), ('gini_pro', 'Gini Pro')], default='pro', max_length=20),
        ),
    ]
