# Generated by Django 4.2.17 on 2026-04-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0023_add_cloud_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cloudnotification',
            new_name='admin_porta_is_read_c4a45d_idx',
            old_name='admin_porta_is_read_idx',
        ),
    ]
