# Generated by Django 4.2.17 on 2026-07-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0024_rename_admin_porta_is_read_idx_admin_porta_is_read_c4a45d_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudNotification',
        ),
    ]
