# Generated by Django 4.2.17 on 2026-07-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0025_delete_cloudnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentationJob',
        ),
    ]
