# Generated by Django 4.2.17 on 2026-07-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0027_savedprompt_project_conversation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pptx_error',
            field=models.TextField(blank=True, default='', help_text='Error message if PPTX generation failed'),
        ),
        migrations.AddField(
            model_name='message',
            name='pptx_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='', help_text='Status of async PPTX generation (blank = not a presentation message)', max_length=20),
        ),
    ]
