# Generated by Django 4.2.17 on 2026-07-23 19:35
#
# Removes the redundant ['conversation', 'created_at'] index on Message —
# the surviving ['conversation', '-created_at'] index serves both directions
# (Postgres can scan a btree backward for the equality-filtered leading
# column 'conversation' at no extra cost), so the ascending twin was pure
# write overhead. Uses RemoveIndexConcurrently (requires atomic = False) so
# this doesn't take a blocking lock on a live 'message' table in production.

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # required by RemoveIndexConcurrently

    dependencies = [
        ('admin_portal', '0028_add_pptx_status_to_message'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='message',
            name='admin_porta_convers_eea95a_idx',
        ),
    ]
