# Generated by Django 4.2.17 on 2026-07-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0029_remove_message_admin_porta_convers_eea95a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='export_error',
            field=models.TextField(blank=True, default='', help_text='Error message if file export failed'),
        ),
        migrations.AddField(
            model_name='message',
            name='export_file_type',
            field=models.CharField(blank=True, choices=[('docx', 'Word'), ('pdf', 'PDF'), ('xlsx', 'Excel')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='export_file_url',
            field=models.CharField(blank=True, default='', help_text='URL to this reply rendered as a downloadable file', max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='export_status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='', help_text='Status of rendering this reply as a file (blank = no export requested)', max_length=20),
        ),
    ]
