# Generated by Django 4.2.17 on 2026-07-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0030_message_export_error_message_export_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_export_ack',
            field=models.BooleanField(default=False, help_text="True when this message's content is just the short 'here's your file' acknowledgment from a pure export request (no LLM call was made) — NOT real material, so a later pure export must skip past it when looking for the last real reply to re-render, or repeated 'download link' asks would keep exporting the previous ack instead of the original content."),
        ),
    ]
