# Generated by Django 4.2.17 on 2026-07-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0031_message_is_export_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_export_format',
            field=models.CharField(blank=True, default='', help_text="Format of the most recent file export in this conversation (docx/pdf/xlsx/csv/md/pptx) — lets a vague follow-up like 'give me that too' or 'send it again' reuse the same format instead of guessing docx.", max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='export_file_type',
            field=models.CharField(blank=True, choices=[('docx', 'Word'), ('pdf', 'PDF'), ('xlsx', 'Excel'), ('pptx', 'PowerPoint'), ('csv', 'CSV'), ('md', 'Markdown')], default='', max_length=10),
        ),
    ]
