# Generated by Django 4.2.17 on 2026-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0032_conversation_last_export_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='provider_kind',
            field=models.CharField(choices=[('chat', 'Chat / Text'), ('image', 'Image Generation')], db_index=True, default='chat', help_text='chat = shows in the model picker; image = used only by Presentation mode to illustrate image_placeholder slides', max_length=10),
        ),
    ]
