# Generated by Django 4.2.17 on 2026-07-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0033_llmprovider_provider_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='cached_input_cost_per_1m',
            field=models.FloatField(default=0.0, help_text='Cost per 1 million cached-input tokens in USD (0 if the model/deployment has no prompt caching)'),
        ),
    ]
