# Generated by Django 4.2.17 on 2026-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0034_llmprovider_cached_input_cost_per_1m'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusagelog',
            name='cached_tokens',
            field=models.IntegerField(default=0, help_text="Portion of prompt_tokens served from the provider's prompt cache (0 if the model/request had no cache hit, or the provider does not report it)"),
        ),
    ]
