# Generated by Django 4.2.17 on 2026-09-15 08:17

import admin_portal.vector_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def enable_vector(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('CREATE EXTENSION IF NOT EXISTS vector')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0036_conversation_context'),
    ]

    operations = [
        migrations.RunPython(enable_vector, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='conversation',
            name='chat_mode',
            field=models.CharField(choices=[('general', 'General Chat'), ('code', 'Code Assistant'), ('summarize', 'Summarizer'), ('document', 'Document Q&A'), ('knowledge', 'Company Knowledge'), ('presentation', 'Presentation Creator')], db_index=True, default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='knowledge_private/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('embedding_model', models.CharField(blank=True, default='', max_length=255)),
                ('embedding_dimensions', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='knowledge_grants', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('embedding', admin_portal.vector_field.VectorField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='admin_portal.knowledgedocument')),
            ],
        ),
        migrations.AddConstraint(
            model_name='embeddingchunk',
            constraint=models.UniqueConstraint(fields=('document', 'version', 'chunk_index'), name='unique_knowledge_chunk'),
        ),
    ]
