# Generated by Django 4.2.17 on 2026-09-15 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0037_enterprise_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='operation',
            field=models.CharField(default='convert', max_length=30),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='progress_stage',
            field=models.CharField(blank=True, default='Queued', max_length=100),
        ),
        migrations.CreateModel(
            name='WebSearchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_search_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='conversions/input/')),
                ('position', models.PositiveIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_inputs', to='admin_portal.conversionjob')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='websearchusage',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_web_usage'),
        ),
    ]
