"""
Django settings for multimodel project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [host.strip() for host in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_celery_results',
    'accounts',
    'admin_portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware must sit as high as possible — above WhiteNoise (or any
    # other middleware that can short-circuit and return a response) — so
    # CORS headers are still attached to responses those middlewares generate.
    # See: https://github.com/adamchainz/django-cors-headers#setup
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'multimodel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'multimodel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')
DB_NAME = config('DB_NAME', default=str(BASE_DIR / 'db.sqlite3'))
DB_USER = config('DB_USER', default='')
DB_PASSWORD = config('DB_PASSWORD', default='')
DB_HOST = config('DB_HOST', default='')
DB_PORT = config('DB_PORT', default='')

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME', default='gini_db'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='5432'),
        # FIX (DB connection pooling): CONN_MAX_AGE=60 reuses DB connections
        # within the same thread/worker for up to 60 seconds.
        # Previously 600s — too long for multi-process deployments (uvicorn + celery
        # each hold their own connections, exhausting the DB pool).
        # 60s is a balance: enough to reuse across most requests, short enough
        # to release connections during idle periods.
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django 4.2+ STORAGES format (replaces deprecated STATICFILES_STORAGE)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication Backends
# Support both local authentication (ModelBackend) and custom backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Local authentication support
]

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('THROTTLE_ANON', default='20/minute'),
        'user': config('THROTTLE_USER', default='120/minute'),
        # Document conversion/OCR is far more expensive per-request than the
        # blanket user rate accounts for (Celery now bounds worker-thread
        # blocking, but a user could still queue up an unbounded number of
        # these jobs at the generic 120/minute rate).
        'document_conversion': config('THROTTLE_DOCUMENT_CONVERSION', default='5/minute'),
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': config('DEFAULT_PAGE_SIZE', default=50, cast=int),
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    # Short-lived — access tokens can't be blacklisted (only refresh tokens
    # can), so keeping this short limits the exposure window if one leaks.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # Rotate on every refresh + blacklist the old one — makes a stolen
    # refresh token single-use instead of valid for its whole lifetime.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Authentication Settings
ALLOW_LOCAL_AUTH = config('ALLOW_LOCAL_AUTH', default=True, cast=bool)

# Azure AD (OpenID Connect)
AZURE_AD_ENABLED = config('AZURE_AD_ENABLED', default=False, cast=bool)
AZURE_AD_TENANT_ID = config('AZURE_AD_TENANT_ID', default='')
AZURE_AD_CLIENT_ID = config('AZURE_AD_CLIENT_ID', default='')
AZURE_AD_CLIENT_SECRET = config('AZURE_AD_CLIENT_SECRET', default='')
AZURE_AD_REDIRECT_URI = config('AZURE_AD_REDIRECT_URI', default='')
# Where to send the user after the backend receives the OAuth callback from Azure.
# This should be the frontend auth/callback page.
AZURE_AD_FRONTEND_REDIRECT_URI = config('AZURE_AD_FRONTEND_REDIRECT_URI', default='http://localhost:5173/auth/callback')
AZURE_AD_LOGOUT_REDIRECT_URI = config('AZURE_AD_LOGOUT_REDIRECT_URI', default='')
AZURE_AD_SCOPES = config('AZURE_AD_SCOPES', default='openid profile email').split()
AZURE_AD_ALLOW_LOCAL_ADMIN = config('AZURE_AD_ALLOW_LOCAL_ADMIN', default=True, cast=bool)
AZURE_AD_AUTO_PROVISION = config('AZURE_AD_AUTO_PROVISION', default=True, cast=bool)
AZURE_AD_GRAPH_ENABLED = config('AZURE_AD_GRAPH_ENABLED', default=False, cast=bool)
AZURE_AD_GRAPH_SCOPES = config('AZURE_AD_GRAPH_SCOPES', default='https://graph.microsoft.com/.default').split()

# Ollama
OLLAMA_BASE_URL = config('OLLAMA_BASE_URL', default='http://localhost:11434')
OLLAMA_MODEL = config('OLLAMA_MODEL', default='llama3:1b')


# Request queue
# Increase default concurrency to 5 to allow several parallel LLM requests
QUEUE_CONCURRENCY = config('QUEUE_CONCURRENCY', default=5, cast=int)
# Allow a reasonable buffer of queued requests (0 = unlimited)
QUEUE_MAX_SIZE = config('QUEUE_MAX_SIZE', default=100, cast=int)

# CORS settings — driven from .env
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in config(
        'CORS_ALLOWED_ORIGINS',
        default='http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8081'
    ).split(',')
    if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# LLM API Keys — referenced by LLMProvider.api_key_env_var (DB-driven)
# These settings remain for backward compatibility during migration.
# New providers should store their env var name in the DB.
AZURE_OPENAI_API_KEY = config('AZURE_OPENAI_API_KEY', default='')
AZURE_OPENAI_ENDPOINT = config('AZURE_OPENAI_ENDPOINT', default='')
AZURE_OPENAI_API_VERSION = config('AZURE_OPENAI_API_VERSION', default='')
AZURE_OPENAI_DEPLOYMENT = config('AZURE_OPENAI_DEPLOYMENT', default='')
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
CLAUDE_API_KEY = config('CLAUDE_API_KEY', default='')
HUGGINGFACE_API_KEY = config('HUGGINGFACE_API_KEY', default='')

# File upload settings
MAX_UPLOAD_SIZE_MB = config('MAX_UPLOAD_SIZE_MB', default=25, cast=int)
ALLOWED_UPLOAD_TYPES = config('ALLOWED_UPLOAD_TYPES', default='pdf,docx,txt,md,csv,xlsx').split(',')
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE_MB * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE_MB * 1024 * 1024

# ---------------------------------------------------------------------------
# Production Security Settings
# ---------------------------------------------------------------------------
if not DEBUG:
    # HTTPS / proxy settings
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True

# X-Frame-Options: SAMEORIGIN allows Django admin to work in frames on same domain
X_FRAME_OPTIONS = 'DENY'

# CSRF trusted origins (required for Django 4.x behind a proxy). No default —
# an un-configured deployment should trust nothing rather than silently trust
# a domain hardcoded here that may have no relation to where this is running.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config(
        'CSRF_TRUSTED_ORIGINS',
        default=''
    ).split(',')
    if origin.strip()
]

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} [{name}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'django.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'admin_portal': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================================================
# Redis — Distributed Cache
# FIX: Django ka default in-memory cache sirf ek process mein kaam karta hai.
#      Multiple uvicorn workers ya Celery workers ke saath har process ki apni
#      alag cache hoti hai — rate limits, session data share nahi hote.
#      Redis ek shared cache provide karta hai sabke liye.
# ============================================================================
REDIS_URL = config('REDIS_URL', default='')

# Use Redis cache when REDIS_URL is configured (Docker / production).
# Fall back to local-memory cache for local dev (no Redis required).
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'db': '1',              # DB 0 = Celery broker, DB 1 = cache
            },
            'KEY_PREFIX': 'gini',
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'gini-local',
            'TIMEOUT': 300,
        }
    }

# ============================================================================
# Celery — Async Task Queue
# General-purpose background job infrastructure: separate worker process(es),
# shared across backend instances via the Redis broker, scalable independently
# of the web process, and persistent across backend restarts.
# ============================================================================
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='django-db')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

CELERY_TASK_TIME_LIMIT = 300          # Hard kill after 5 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 240     # Soft warning at 4 minutes

CELERY_TASK_DEFAULT_QUEUE = 'default'

# Route light, fast "chat_post" work (summarization, usage logging) and heavy
# "documents" work (PPTX rendering, OCR, format conversion) to separate
# queues, so a backlog of slow document jobs can never starve chat
# post-processing. Matches the `-Q chat_post` / `-Q documents` queue names
# consumed by the celery-worker services in docker-compose.yml.
CELERY_TASK_ROUTES = {
    'admin_portal.tasks.summarize_conversation_task': {'queue': 'chat_post'},
    'admin_portal.tasks.chat_stream_post_process_task': {'queue': 'chat_post'},
    'admin_portal.tasks.generate_pptx_task': {'queue': 'documents'},
    'admin_portal.tasks.convert_document_task': {'queue': 'documents'},
    'admin_portal.tasks.extract_text_task': {'queue': 'documents'},
}

# Store task results in DB via django-celery-results — lets admin inspect
# failed tasks from the Django admin panel.
CELERY_RESULT_EXTENDED = True

# Wall-clock cap on a single SSE streaming LLM response (ChatStreamView) —
# see llm_queue.py's stream_semaphore/stream_timeout gate.
STREAM_TIMEOUT_SECONDS = config('STREAM_TIMEOUT_SECONDS', default=300, cast=int)

# Public origin the backend is reachable at, used to build absolute media
# URLs (e.g. generated PPTX files) from Celery tasks, which have no
# request object to call request.build_absolute_uri() on. Leave blank in
# same-origin deployments (nginx proxying /media/ on the same host as the
# frontend) where a MEDIA_URL-relative path already resolves correctly.
BACKEND_PUBLIC_URL = config('BACKEND_PUBLIC_URL', default='').rstrip('/')