import Link from "@/components/site-link";
import { ArrowUpRight, ArrowDown, Layers3, Workflow, ShieldCheck, Network, LockKeyhole, Eye, UserRoundCheck, Split, Repeat2, Unplug, ScanLine } from "lucide-react";
import { Button, SectionHeading } from "@/components/ui";
import { SystemVisual } from "@/components/system-visual";
import { LogoMark } from "@/components/brand";
import { ApproachSequence, ProductPortfolio, IntegrationExplorer, IndustrySelector, AutomationIntake } from "@/components/home-interactions";
import { pillars } from "@/content/site";

const pillarIcons = [Layers3, Network, Workflow, ShieldCheck];
const friction = [{ icon: Split, title: "Fragmented AI tools", body: "More tools, without a connected way of working." }, { icon: Repeat2, title: "Repetitive processes", body: "Time spent on work that could be automated." }, { icon: Unplug, title: "Disconnected systems", body: "Intelligence sitting outside everyday operations." }, { icon: ScanLine, title: "Limited visibility", body: "AI adoption without a clear view of access and use." }];

export default function HomePage() {
  return <>
    <section className="hero container" aria-labelledby="hero-title"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> INTELLIGENCE, WITH INTENT</span><h1 id="hero-title">Enterprise AI.<br/><span>Built for</span><br/>Real Work<span className="hero-period">.</span></h1><p>Practical AI products, connected systems, and intelligent automation. Built around your business. With people in control.</p><div className="button-group"><Button href="/contact" icon={<ArrowUpRight/>}>Talk to Matenix AI</Button><Button href="/solutions" variant="ghost" icon={<ArrowUpRight/>}>Explore Solutions</Button></div><div className="hero-note"><span className="hero-note-line"/> Designed for the realities of enterprise.</div></div><SystemVisual/><div className="hero-bottom"><span>FROM AI POTENTIAL TO EVERYDAY OPERATIONS</span><a href="#capabilities" aria-label="Discover Matenix capabilities">Discover Matenix <ArrowDown aria-hidden="true"/></a></div></section>

    <section id="capabilities" className="capability-strip" aria-label="Our capabilities"><div className="container capability-grid">{pillars.map((pillar, i) => { const Icon = pillarIcons[i]; return <Link key={pillar.slug} href={pillar.href}><span className="capability-number">{pillar.number}</span><Icon aria-hidden="true"/><span>{["AI Products", "System Integration", "AI Automation", "AI Governance"][i]}</span><ArrowUpRight aria-hidden="true"/></Link>; })}</div></section>

    <section className="container section problem-section"><div className="problem-heading"><span className="eyebrow">01 / THE CHALLENGE</span><h2 className="section-title">AI shouldn’t create<br/>another layer of <span className="text-secondary">complexity.</span></h2><p className="body-large text-secondary">Technology should make work simpler. Too often, it adds another tool, another process, another disconnect.</p></div><div className="friction-grid">{friction.map(item => <div key={item.title} className="friction-item"><item.icon aria-hidden="true"/><h3>{item.title}</h3><p>{item.body}</p></div>)}</div><div className="approach-heading"><span className="eyebrow">THE MATENIX APPROACH</span><p>Start with the problem.<br/><span className="text-secondary">Put intelligence where it matters.</span></p></div><ApproachSequence/></section>

    <section id="products" className="portfolio-section section"><div className="container"><SectionHeading eyebrow="02 / OUR PRODUCT PORTFOLIO" title={<>Purpose-built intelligence.<br/><span className="text-secondary">Real operational value.</span></>} description="Three complementary capabilities. One practical approach to enterprise AI." aside={<Link href="/products" className="text-link">All products <ArrowUpRight aria-hidden="true"/></Link>}/><ProductPortfolio/><p className="portfolio-framing">Beyond our products, Matenix AI can integrate these capabilities into existing enterprise environments or develop purpose-built AI automation for specific business requirements.</p></div></section>

    <section className="container section integration-section"><div className="integration-copy"><span className="eyebrow">03 / CONNECTED INTELLIGENCE</span><h2 className="section-title">Your systems.<br/>Working <span className="text-secondary">smarter.</span></h2><p className="body-large text-secondary">An intelligence layer for the enterprise you already have.</p><p className="text-secondary">We connect AI with existing applications, workflows and business technology, so you can build on what already works.</p><Button href="/system-integration" variant="secondary" icon={<ArrowUpRight/>}>Explore System Integration</Button><div className="integration-principle"><Layers3 aria-hidden="true"/><span>Integrate with what works.<br/>Build around what matters.</span></div></div><IntegrationExplorer/></section>

    <section className="automation-section"><div className="container automation-grid"><div><span className="eyebrow">04 / CUSTOM AI AUTOMATION</span><h2 className="section-title">Your process isn’t<br/>off the shelf.<br/><span className="text-secondary">Your AI needn’t be.</span></h2><p className="body-large text-secondary">Have a business process that doesn’t fit an off-the-shelf product?</p><p className="text-secondary">We design and develop AI-powered automation around your specific workflows, tasks and operational needs.</p><Link href="/ai-automation" className="text-link">Explore custom automation <ArrowUpRight aria-hidden="true"/></Link></div><AutomationIntake/></div></section>

    <section className="container section"><SectionHeading eyebrow="05 / BUILT FOR YOUR WORLD" title={<>Different industries.<br/><span className="text-secondary">Shared operational realities.</span></>} description="Every organisation works differently. We start with yours."/><IndustrySelector/></section>

    <section className="trust-section"><div className="container section"><div className="trust-heading"><span className="eyebrow">06 / ENTERPRISE BY DESIGN</span><h2 className="section-title">Intelligence works best<br/>when <span className="text-secondary">you’re in control.</span></h2><p className="body-large text-secondary">Privacy, security and governance belong in the conversation from the start. They shape how we approach enterprise AI.</p></div><div className="trust-grid">{[{ icon: LockKeyhole, title: "Privacy & security", copy: "Build around your organisation’s data boundaries and security requirements." }, { icon: Eye, title: "Visibility & governance", copy: "Take a structured approach to AI access, administration and usage visibility." }, { icon: UserRoundCheck, title: "Human oversight", copy: "Keep people in control, particularly when AI takes action on your behalf." }].map(item => <div key={item.title}><item.icon aria-hidden="true"/><h3>{item.title}</h3><p>{item.copy}</p></div>)}</div><div className="trust-bottom"><span>Our design principles. Shaped around your enterprise requirements.</span><Link href="/enterprise-ai-governance" className="text-link">Explore our governance approach <ArrowUpRight aria-hidden="true"/></Link></div></div></section>

    <section className="container section vision-section"><span className="eyebrow"><span className="status-dot"/> THE WAY FORWARD</span><h2>AI that fits into work.<br/><span className="text-secondary">And moves it forward.</span></h2><p>We envision a future where AI becomes a natural part of everyday enterprise operations, working intelligently in the background, removing friction, improving experiences and helping people make better decisions.</p><p>Matenix AI is building that future one practical solution, integration and automation at a time.</p><div className="button-group"><Button href="/contact" icon={<ArrowUpRight/>}>Talk to Matenix AI</Button><Button href="/solutions" variant="ghost" icon={<ArrowUpRight/>}>Explore Solutions</Button></div><div className="vision-brand" aria-hidden="true"><LogoMark size={160}/><div className="vision-wordmark">matenix<span>AI</span></div></div></section>
  </>;
}
